name: college_football_spread_game
description: A college football spread game app.
version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.17.5 
  firebase_core: ^2.32.0  
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.1.0

flutter:
  uses-material-design: true