import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // <-- Make sure this file exists and is generated by flutterfire configure

import 'models/game.dart';
import 'models/leaderboard_entry.dart';
import 'providers/game_provider.dart';
import 'providers/leaderboard_provider.dart';
import 'pages/user_page.dart';
import 'pages/admin_page.dart';
import 'pages/leaderboard_page.dart';
import 'theme.dart'; // Import your custom theme

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // <-- required for web!
  );

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => GameProvider()),
        ChangeNotifierProvider(create: (_) => LeaderboardProvider()),
      ],
      child: MaterialApp(
        title: 'College Football Spread Game',
        theme: georgiaTechTheme, // Use your custom theme
        initialRoute: '/',
        routes: {
          '/home': (context) => UserPage(),
          '/admin': (context) => AdminPage(),
          '/leaderboard': (context) => LeaderboardPage(),
        },
      ),
    );
  }
}
